name: build
on:
  push:
  workflow_call:

permissions:
  contents: write

jobs:
  slides:
    uses: ./.github/workflows/template_build_latex.yaml
    with:
      tex-workdir: presentation
      tex-file: presentation
      output-name: slides
